// index — spec §7.2, schema §4.8. A pure function of the snapshot's
// frontmatter: sets by order, principles by order, sources by author then
// work then title, open proposals by id, tags by name, all by codepoint.
// tools/gnomon-check.py is the reference; this reproduces it byte for byte.

import type { BrainSnapshot, FileWrite, SetFm, SourceFm } from '../schema/types';
import { renderDualLink } from '../links/index';
import { serializeFile } from '../schema/serialize';

export const INDEX_PATHS = ['principles/_index.md', 'maps/_index.md'] as const;
export type IndexPath = (typeof INDEX_PATHS)[number];

const HEAD = '---\ntype: index\n---\n<!-- GENERATED by Gnomon. Do not edit. Regenerated on every write. -->\n';

/** Compare by Unicode codepoint, locale-independent (schema §4.8). */
export function cmpCodepoint(a: string, b: string): number {
  const ia = a[Symbol.iterator]();
  const ib = b[Symbol.iterator]();
  for (;;) {
    const x = ia.next();
    const y = ib.next();
    if (x.done && y.done) return 0;
    if (x.done) return -1;
    if (y.done) return 1;
    const d = x.value.codePointAt(0)! - y.value.codePointAt(0)!;
    if (d !== 0) return d;
  }
}

/** The user-visible label: `Set {order}` or `Set {order} — {name}` (schema §4.4). */
export function setLabel(fm: SetFm): string {
  return `Set ${fm.order}` + (fm.name ? ` — ${fm.name}` : '');
}

function setsSection(s: BrainSnapshot, from: IndexPath, h: string): string[] {
  const out: string[] = [];
  for (const set of s.sets) {
    out.push(`${h} ${setLabel(set.fm)}\n`);
    const slug = set.path.split('/')[1]!;
    const principles = s.principlesOf(slug);
    if (principles.length === 0) out.push('(no principles)\n');
    else {
      for (const p of principles) {
        out.push(`${p.fm.order}. ${renderDualLink(from, p.path, 'principle')} — ${p.fm.title} — grounds: ${p.fm.grounds.length}`);
      }
      out.push('');
    }
  }
  return out;
}

function finish(lines: string[]): string {
  return lines.join('\n').replace(/\n+$/, '') + '\n';
}

/** Both generated index files (schema §4.8), deterministic from frontmatter alone. */
export function generateIndexes(s: BrainSnapshot): Record<IndexPath, string> {
  const pi = [HEAD, '# Principles\n', ...setsSection(s, 'principles/_index.md', '##')];
  const mi = [HEAD, '# Index\n', '## Principles\n', ...setsSection(s, 'maps/_index.md', '###')];
  const M: IndexPath = 'maps/_index.md';

  const sources = s.byType('source').map((f) => ({ f, fm: f.fm as SourceFm, work: f.fm.work || '' }));
  sources.sort((a, b) => cmpCodepoint(a.fm.author, b.fm.author) || cmpCodepoint(a.work, b.work) || cmpCodepoint(a.fm.title, b.fm.title) || cmpCodepoint(a.f.path, b.f.path));
  mi.push('## Sources\n');
  if (sources.length === 0) mi.push('(no sources)\n');
  else {
    let current: string | undefined;
    for (const { f, fm, work } of sources) {
      if (fm.author !== current) {
        if (current !== undefined) mi.push('');
        mi.push(`### ${fm.author}\n`);
        current = fm.author;
      }
      const extra = (work ? `, ${work}` : '') + (fm.year ? ` (${fm.year})` : '');
      const att = fm.attachment ? ' — attachment' : '';
      const st = fm.curated === 'ratified' || fm.curated === 'human' ? '' : ` — ${fm.curated}`;
      mi.push(`- ${renderDualLink(M, f.path, 'raw')} — ${fm.title}${extra}${att}${st}`);
    }
    mi.push('');
  }

  const proposals = s.byType('proposal').filter((f) => f.fm.status === 'open').sort((a, b) => cmpCodepoint(a.path, b.path));
  mi.push('## Open proposals\n');
  if (proposals.length === 0) mi.push('(none)\n');
  else {
    for (const f of proposals) {
      mi.push(`- ${renderDualLink(M, f.path, 'proposal')} — ${f.fm.kind} — ${f.fm.title}` + (f.fm.target_set ? ` — ${f.fm.target_set}` : ''));
    }
    mi.push('');
  }

  const tags = new Map<string, string[]>();
  for (const f of s.files.values()) {
    const list = f.fm.type === 'index' ? undefined : f.fm.tags;
    for (const t of list ?? []) tags.set(t, [...(tags.get(t) ?? []), f.path]);
  }
  mi.push('## Tags\n');
  if (tags.size === 0) mi.push('(none)\n');
  else {
    for (const t of [...tags.keys()].sort(cmpCodepoint)) {
      const links = tags.get(t)!.sort(cmpCodepoint).map((p) => renderDualLink(M, p, p.endsWith('raw.md') ? 'raw' : 'file'));
      mi.push(`- ${t} — ${links.join(', ')}`);
    }
    mi.push('');
  }

  return { 'principles/_index.md': finish(pi), 'maps/_index.md': finish(mi) };
}

/** The index writes a commit must carry: only the files whose generated text differs from the snapshot (spec §7.2). */
export function indexWrites(s: BrainSnapshot): FileWrite[] {
  const generated = generateIndexes(s);
  const writes: FileWrite[] = [];
  for (const path of INDEX_PATHS) {
    const current = s.files.get(path);
    if (!current || serializeFile(current) !== generated[path]) writes.push({ path, text: generated[path] });
  }
  return writes;
}
