#!/usr/bin/env python3
"""Prototype of `gnomon validate` + `gnomon index` per schema v0.2. Usage: gnomon_check.py <brain> [--write]"""
import os, re, sys, yaml
root=sys.argv[1]; write='--write' in sys.argv
issues=[]
def ref(level,path,msg): issues.append((level,path,msg))

EXEMPT_TOP={'AGENTS.md','README.md'}
files={}
for dp,dn,fn in os.walk(root):
    dn[:]=[d for d in dn if not d.startswith('.')]
    for f in fn:
        p=os.path.relpath(os.path.join(dp,f),root)
        if not f.endswith('.md') or p in EXEMPT_TOP or p.startswith('templates/'): continue
        text=open(os.path.join(root,p)).read()
        m=re.match(r'^---\n(.*?)\n---\n?(.*)$',text,re.S)
        if not m: ref('refusal',p,'no frontmatter'); continue
        try: fm=yaml.safe_load(m.group(1)) or {}
        except Exception as e: ref('refusal',p,f'yaml: {e}'); continue
        files[p]=(fm,m.group(2))

REQ={'source':['title','author'],'notes':['source'],'principle-set':['order'],
     'principle':['title','set','order','grounds'],'inbox':['status'],'proposal':['kind','title','status'],'index':[]}
SLUG=re.compile(r'^[a-z0-9](?:[a-z0-9-]{1,58})[a-z0-9]$')
for p,(fm,body) in files.items():
    t=fm.get('type')
    if t not in REQ: ref('refusal',p,f'bad type {t!r}'); continue
    if t=='index':
        if set(fm)!={'type'}: ref('refusal',p,'index frontmatter must be type only')
        continue
    for k in ['curated','created','updated']+REQ[t]:
        if k not in fm: ref('refusal',p,f'missing {k}')
    if fm.get('curated') not in ('human','agent-proposed','ratified'): ref('refusal',p,'bad curated')
    if t in ('principle','principle-set','inbox') and fm.get('curated')!='human': ref('refusal',p,'must be curated: human')
    if t=='proposal' and fm.get('curated')=='ratified': ref('refusal',p,'proposal never ratified')
    parts=p.split('/')
    if t=='principle' and fm.get('set')!=parts[1]: ref('refusal',p,'set != folder')
    if t=='notes' and fm.get('source')!=parts[1]: ref('refusal',p,'source != folder')
    if t in ('source','notes') and not SLUG.match(parts[1]): ref('refusal',p,'bad slug')
    if t=='principle' and not SLUG.match(parts[2][:-3]): ref('refusal',p,'bad slug')
    if t=='inbox' and fm.get('status')=='filed':
        fa=fm.get('filed_as')
        if not fa or f'sources/{fa}/raw.md' not in files: ref('refusal',p,'filed without valid filed_as')
    if t=='source' and fm.get('attachment') and not os.path.exists(os.path.join(root,os.path.dirname(p),fm['attachment'])):
        ref('refusal',p,'declared attachment missing')
    if t=='principle':
        for g in fm.get('grounds') or []:
            if f'sources/{g}/raw.md' not in files: ref('warning',p,f'grounds -> missing source {g}')
        linked={m for m in re.findall(r'\[\[sources/([a-z0-9-]+)/raw',body)}
        gset=set(fm.get('grounds') or [])
        if linked!=gset: ref('warning',p,f'grounds drift: body {sorted(linked)} vs grounds {sorted(gset)}')
        for r in fm.get('related') or []:
            if f'principles/{r}.md' not in files: ref('warning',p,f'related -> missing {r}')
# source folders hold only allowed files
for d in os.listdir(os.path.join(root,'sources')) if os.path.isdir(os.path.join(root,'sources')) else []:
    dd=os.path.join(root,'sources',d)
    if not os.path.isdir(dd): continue
    fm=files.get(f'sources/{d}/raw.md',({},''))[0]
    allowed={'raw.md','notes.md'}|({fm['attachment']} if fm.get('attachment') else set())
    for f in os.listdir(dd):
        if f not in allowed: ref('refusal',f'sources/{d}/{f}','unexpected file in source folder')
# order contiguity
sets=sorted([(fm['order'],p.split('/')[1],fm) for p,(fm,_) in files.items() if fm.get('type')=='principle-set'])
if [o for o,_,_ in sets]!=list(range(1,len(sets)+1)): ref('refusal','principles/','set order not 1..N')
if not sets: ref('refusal','principles/','no principle set')
princ={}
for p,(fm,_) in files.items():
    if fm.get('type')=='principle': princ.setdefault(fm['set'],[]).append((fm['order'],p,fm))
for s,lst in princ.items():
    lst.sort()
    if [o for o,_,_ in lst]!=list(range(1,len(lst)+1)): ref('refusal',f'principles/{s}','principle order not 1..N')

# ---- index generation
def dual(target, frm, label):
    rel=os.path.relpath(target, os.path.dirname(frm))
    return f'[[{target[:-3]}]] ([{label}]({rel}))'
def label(fm): return f"Set {fm['order']}" + (f" — {fm['name']}" if fm.get('name') else '')
def sets_section(frm, h):
    out=[]
    for o,slug,fm in sets:
        out.append(f'{h} {label(fm)}\n')
        lst=princ.get(slug,[])
        if not lst: out.append('(no principles)\n')
        else:
            for po,pp,pfm in lst:
                out.append(f"{po}. {dual(pp,frm,'principle')} — {pfm['title']} — grounds: {len(pfm.get('grounds') or [])}")
            out.append('')
    return out
HEAD='---\ntype: index\n---\n<!-- GENERATED by Gnomon. Do not edit. Regenerated on every write. -->\n'
pi=[HEAD,'# Principles\n']+sets_section('principles/_index.md','##')
mi=[HEAD,'# Index\n','## Principles\n']+sets_section('maps/_index.md','###')
srcs=sorted([(fm['author'],fm.get('work') or '',fm['title'],p,fm) for p,(fm,_) in files.items() if fm.get('type')=='source'])
mi.append('## Sources\n')
if not srcs: mi.append('(no sources)\n')
else:
    cur=None
    for a,w,t,p,fm in srcs:
        if a!=cur:
            if cur is not None: mi.append('')
            mi.append(f'### {a}\n'); cur=a
        extra=(f", {w}" if w else '')+(f" ({fm['year']})" if fm.get('year') else '')
        att=' — attachment' if fm.get('attachment') else ''
        st='' if fm['curated'] in ('ratified','human') else f" — {fm['curated']}"
        mi.append(f"- {dual(p,'maps/_index.md','raw')} — {t}{extra}{att}{st}")
    mi.append('')
props=sorted([(p,fm) for p,(fm,_) in files.items() if fm.get('type')=='proposal' and fm.get('status')=='open'])
mi.append('## Open proposals\n')
if not props: mi.append('(none)\n')
else:
    for p,fm in props: mi.append(f"- {dual(p,'maps/_index.md','proposal')} — {fm['kind']} — {fm['title']}"+(f" — {fm['target_set']}" if fm.get('target_set') else ''))
    mi.append('')
tags={}
for p,(fm,_) in files.items():
    for t in fm.get('tags') or []: tags.setdefault(t,[]).append(p)
mi.append('## Tags\n')
if not tags: mi.append('(none)\n')
else:
    for t in sorted(tags): mi.append(f"- {t} — "+', '.join(dual(p,'maps/_index.md','raw' if p.endswith('raw.md') else 'file') for p in sorted(tags[t])))
    mi.append('')
gen={'principles/_index.md':'\n'.join(pi).rstrip('\n')+'\n','maps/_index.md':'\n'.join(mi).rstrip('\n')+'\n'}
for p,txt in gen.items():
    cur=open(os.path.join(root,p)).read() if os.path.exists(os.path.join(root,p)) else None
    if cur!=txt:
        if write: open(os.path.join(root,p),'w').write(txt); print(f'index: wrote {p}')
        else: print(f'index: {p} is STALE')
    else: print(f'index: {p} up to date')
for lvl,p,msg in sorted(issues): print(f'{lvl.upper():8} {p}: {msg}')
print(f'{len(files)} files, {sum(1 for i in issues if i[0]=="refusal")} refusals, {sum(1 for i in issues if i[0]=="warning")} warnings')
sys.exit(1 if any(i[0]=='refusal' for i in issues) else 0)
